### PR TITLE
Rank exact-name matches first in search results

### LINKED ISSUE #42: `search-external` substring matching swamps real hits with derived names
### Description

`search-external <query>` returns any symbol containing `<query>` as a
substring, ranked only by what looks like declaration order. For short
or common tokens (`Monad`, `List`, `Map`, `Map`, `Cursor`, `Meta`),
the top of the result list is dominated by names that *contain* the
query rather than names that *are* the query, so the actually-relevant
hit is buried.

Real example I hit while looking up `cats.Monad`: I had to scroll past
`MonadError`, `MonadOps`, `Bimonad`, `Comonad`, `IdTMonad`, `RWSTMonad`,
`KleisliMonad`, `WriterTMonad`, `MonadSyntax`, etc., to confirm that
`cats.Monad` itself was even present.

### Steps to reproduce

```sh
cellar search-external org.typelevel:cats-core_3:2.10.0 Monad | head -20
```

### Expected

Either:

- `cats.Monad` (object + trait) appears at the top, because it's the
  symbol whose name *equals* the query, OR
- A flag like `--exact`, `--whole-word`, or `--name-equals` exists to
  force this ranking explicitly.

### Actual

51 results returned. The first few rows are the right ones (`cats.Monad`
trait + `object Monad`), but they're immediately followed by
`Bimonad`, `Comonad`, then a long tail of derived classes:

```
cats.Monad — object Monad
cats.Monad — trait Monad[F] extends FlatMap[F] with Applicative[F]
cats.Monad$ — object Monad$
cats.Bimonad — object Bimonad
cats.Bimonad — trait Bimonad[F] extends Monad[F] with Comonad[F]
cats.Comonad — object Comonad
cats.Comonad — trait Comonad[F] extends CoflatMap[F]
cats.Bimonad$ — object Bimonad$
cats.Comonad$ — object Comonad$
cats.data.IdTMonad — trait IdTMonad[F] extends Monad[TypeLambda] with IdTApplicative[F] with IdTFlatMap[F]
cats.syntax.MonadOps — class MonadOps[F, A] extends AnyVal
cats.data.RWSTMonad — class RWSTMonad[F, E, L, S] extends IRWSTFunctor[F, E, L, S, S] with Monad[TypeLambda]
cats.data.IorTMonad — trait IorTMonad[F, A] extends Monad[TypeLambda] with IorTFunctor[F, A]
cats.MonadError — object MonadError
cats.MonadError — trait MonadError[F, E] extends ApplicativeError[F, E] with Monad[F]
cats.syntax.MonadIdOps — class MonadIdOps[A] extends AnyVal
cats.MonadError$ — object MonadError$
cats.syntax.MonadSyntax — trait MonadSyntax
cats.data.KleisliMonad — trait KleisliMonad[F, A] extends Monad[TypeLambda] with KleisliFlatMap[F, A] with KleisliApplicative[F, A]
cats.data.WriterTMonad — trait WriterTMonad[F, L] extends WriterTApplicative[F, L] with WriterTFlatMap1[F, L] with Monad[TypeLambda]
```

### Proposal

One or both of:

1. **Rank exact-name matches first.** A symbol whose final segment
   equals the query verbatim should sort above a symbol that merely
   contains the query as a substring. Sub-rank by the standard name
   tier (object/trait/class) and then declaration order.
2. **Add `--exact` / `--whole-word` flag** for users who want to opt in
   explicitly. Implementation can be as simple as filtering results to
   `name == query || name == query + "$"`.

Option 1 is a strict UX improvement and matches what most "search by
symbol name" tools (LSP, IDEs, `gh search code`) already do. Option 2
is a smaller change.

### PR DESCRIPTION
**Pull request by rkrzewski**
Replace length-only sort with a tuple key (exact, prefix, length, name) so short substring siblings like `Bimonad`/`MonadError` no longer crowd out the exact `Monad` hit the user actually typed.

Fixes #42

### CODE REVIEW

File: lib/src/cellar/handlers/SearchHandler.scala [hunk 1]
```diff
@@ -53,3 +54,13 @@ object SearchHandler:
         }.flatMap(Console[IO].println)
       } >> note.as(ExitCode.Success)
     }
+
+  /**
+   * Sort key for search results. `lowerQuery` must already be lower-cased.
+   * Order: exact name match → prefix match → shorter name → alphabetical.
+   */
+  private[cellar] def rankKey(lowerQuery: String, name: String): (Int, Int, Int, String) =
```
Comment (rochala) [inline lib/src/cellar/handlers/SearchHandler.scala:62]: Maybe lets just put query here and call toLowerCase inside the method and then remove the requirement from javadoc

**Review by rochala — APPROVED** [review]

File: lib/src/cellar/handlers/SearchHandler.scala (hunk 1 above)
Comment (rkrzewski) [reply lib/src/cellar/handlers/SearchHandler.scala:62]: The only call site for `rankKey` at this point is a `runCore` method in the same class. The query is lowercased in there, at line 37. Perhaps the should adjust the scaladoc comment rather than lowercasing the query twice? "Assume the query was converted to lower case by the caller"?

Comment (rochala) [reply lib/src/cellar/handlers/SearchHandler.scala:62]: Ok, I think its ok to avoid lowercasing multiple times. Lets leave it as it is as both scaladoc and parameter name both suggest it has to be like that
